[project]
name = "sklser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Antal Buss" }
]
requires-python = ">=3.11"
dependencies = [
    "scikit-learn>=1.7.2",
]

[tool.pyrefly]
project-includes = ["**/*"]
project-excludes = [
    "**/node_modules",
    "**/__pycache__",
    "**/*venv/**/*",
]

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"

[tool]
